### ISSUE TITLE
WIP: multiple changes to backend structure

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#231]
- [x] implement sorted adjacency lists (#232, see below)
- [x] remove `unsafe_add_edge!()` and modify `add_edge!()` to silently accept (and discard) duplicates (#232)
- [x] close #20.
- [x] get rid of edge sets in favor of efficient edge iterators (#237)
- [ ] create edge indices - possibly - and get rid of Dict mappings for edges.

**Comment by sbromberger** [comment]
Expected performance impacts:

Getting rid of edge sets will drop `has_edge()` tests from O(1) to O(deg). Adding sorted adjacency lists can improve this to O(log(deg)).

Assuming no more edge sets, adding sorted adjacency lists drops `add_edge!()` from O(1) to O(deg) (possibly faster).

Removing `unsafe_add_edge!()` gives @jpfairbanks an early Christmas present (re-closes #20).

**Comment by sbromberger** [comment]
cc @CarloLucibello

**Comment by sbromberger** [comment]
Real-world performance results for #232. At first glance, this seems very slow.

first setup:
```
es = zeros(Float64,100);
for i = 1:100
       es[i] = @elapsed CompleteGraph(1500)
       print(".")
end
```

old:
```
describe(es)
Summary Stats:
Mean:         0.231058
Minimum:      0.194311
1st Quartile: 0.208941
Median:       0.232086
3rd Quartile: 0.246300
Maximum:      0.337898
```

new:
```
describe(es)
Summary Stats:
Mean:         0.769642
Minimum:      0.697841
1st Quartile: 0.714636
Median:       0.741868
3rd Quartile: 0.791301
Maximum:      1.251975
```

second setup: for the ultimate connected sparsegraph (`PathGraph(1124251)`):

old:
```
describe(es)
Summary Stats:
Mean:         0.450984
Minimum:      0.305043
1st Quartile: 0.416154
Median:       0.449056
3rd Quartile: 0.464965
Maximum:      0.681482
```

new:
```
describe(es)
Summary Stats:
Mean:         0.975703
Minimum:      0.895639
1st Quartile: 0.915645
Median:       0.923949
3rd Quartile: 0.945255
Maximum:      1.675345
```

**Comment by jpfairbanks** [comment]
the first step is to benchmark sorted insertion from stefan's function.

Then maybe we have to go to a blocked adjacency list for this.
```
[1|2|3|ptr]->[4|5|6|ptr]->...->[n-1|n|end]
```

We should probably replace edge sets with edge iterators, we could also provide a function to sort the input edges so that when you insert them, the graph will be constructed in sorted order.

**Comment by sbromberger** [comment]
What I don't quite understand is why sparse matrices are slower to create. The sorting and insertion is essentially O(1) at that point.

**Comment by sbromberger** [comment]
OK, please check out two PRs: the first, #232, does sorted adjacency lists and the second, #234, implements @CarloLucibello's edge iterators (renamed, and with `getindex`).

**Comment by sbromberger** [comment]
with #232, we're approaching edge set speed for completegraph(1500):

```
julia> describe(es)
Summary Stats:
Mean:         0.498594
Minimum:      0.439918
1st Quartile: 0.475205
Median:       0.488157
3rd Quartile: 0.499523
Maximum:      0.705516
```

**Comment by sbromberger** [comment]
And optimizing the insert/dedup, we're now at
completegraph:
```
julia> describe(es)
Summary Stats:
Mean:         0.348433
Minimum:      0.306033
1st Quartile: 0.327904
Median:       0.336862
3rd Quartile: 0.348100
Maximum:      0.463871
```

pathgraph:
```
julia> describe(es)
Summary Stats:
Mean:         0.516862
Minimum:      0.475574
1st Quartile: 0.491386
Median:       0.498166
3rd Quartile: 0.519441
Maximum:      0.760023
```

**Comment by jpfairbanks** [comment]
Can you plot the run time for increasing sizes of graphs?
We know that in the worst case it's `O(d + logd)`. But if the edges are presented in sorted order, the insertion cost should be amortized `O(1)` (1 in d insertions require growing the vector which is d time).

**Comment by sbromberger** [comment]
@jpfairbanks do you want increasing sizes of completegraphs?

**Comment by sbromberger** [comment]
```
_insert_and_dedup!(v::Vector{Int}, x::Int) = isempty(splice!(v, searchsorted(v,x), x))
```

completegraph:
```
julia> describe(es)
Summary Stats:
Mean:         0.335892
Minimum:      0.285435
1st Quartile: 0.310774
Median:       0.322949
3rd Quartile: 0.344336
Maximum:      0.481882
```

pathgraph:
```
julia> describe(es)
Summary Stats:
Mean:         0.501750
Minimum:      0.467093
1st Quartile: 0.480389
Median:       0.488451
3rd Quartile: 0.499828
Maximum:      0.707022
```

**Comment by jpfairbanks** [comment]
both would be good.

**Comment by sbromberger** [comment]
ok. Here's the first set of graphs. This is the mean time to generate 25 completegraphs from n=1 to 2000. The first plot is the absolute mean time to create graph of size *n*; the second graph is the average time per edge.

![iterm2 yalt7a](https://cloud.githubusercontent.com/assets/941359/11212281/bd675974-8ce9-11e5-8fc4-a05fc5fc2ce2.png)


![iterm2 bjorrn](https://cloud.githubusercontent.com/assets/941359/11212284/c2f6719a-8ce9-11e5-8767-500d3f392cc4.png)


Raw data here: https://gist.github.com/sbromberger/9c5d7a658a7b7ef6a133

**Comment by CarloLucibello** [comment]
This is after #232? If so, from the second plot I would say that complete graph construction is O(N^2), at least looking at x > 100 (the change of slope at x~1000 is weird by the way). I was expecting it to be O(N^2) after #232 and O(N^3) after, mmhmhhm

**Comment by sbromberger** [comment]
This is indeed after #232. The bottom graph shows that per-edge insertion is fairly constant regardless of adjacency length.

**Comment by sbromberger** [comment]
Here's pathgraph(n) repeated 25 times each for n = 150,001 to 155,000:

![iterm2 k5e9dx](https://cloud.githubusercontent.com/assets/941359/11231716/42f269aa-8d60-11e5-955f-32da69504197.png)

Normalized by number of edges:

![iterm2 eyab4a](https://cloud.githubusercontent.com/assets/941359/11231723/51599356-8d60-11e5-8d2e-dafeaaf8f4a4.png)


Raw data here: https://gist.github.com/sbromberger/3ed5cbbf71ea9bd26271

**Comment by CarloLucibello** [comment]
Can you do some test also on random (sparse) graph generation?

**Comment by sbromberger** [comment]
Can do. It'll take a while to set it up though, so give me a few days. I don't mind the delay since it means folks are reviewing this well, and it's a fairly significant change.

**Comment by sbromberger** [comment]
I'm going to use nlist for the number of vertices and peg edges to 4*nv. I'll also use the new random seed functionality so that we're comparing the exact same graphs.

**Comment by sbromberger** [comment]
Edgeiter is definitely problematic:

```
julia> function domkg(n::Int, k::Int)
       t = 0.0
       for i = 1:k
       t += @elapsed(Graph(n,4*n,1))
       end
       return t / k
       end
domkg (generic function with 1 method)
julia> domkg(10,50)
0.0003834897

julia> domkg(100,50)
0.006804545519999999

julia> domkg(1000,50)
0.6799213984399999

julia> domkg(1000,5)
0.6660853189999999

julia> domkg(10000,5)
87.0226275228
```

**Comment by sbromberger** [comment]
I think the problem here is that `has_edge()` is using `x in edges(g)` instead of the direct adjacency list checking. Let me rerun the tests.

**Comment by sbromberger** [comment]
OK, here's what I think I'm going to do (as separate PRs):

1) Merge #232. This will give us sorted adjlists.
2) Modify has_edge, and introduce an inefficient edgeiter. We need to make edge iteration more performant but I don't see this as a stumbling point since `edges()` will still use the edge sets.
3) Once we're happy with edge iteration, remove edge sets.

I will start this off by merging #232 on Wednesday the 25th unless there are objections.

cc @jpfairbanks @CarloLucibello

**Comment by CarloLucibello** [comment]
Could you please do the same comparison with domkg between master and sorted adjlist with ne=10*nv?

**Comment by sbromberger** [comment]
master with avg degree=10:
```
julia> domkg(100,50)
0.0003590274

julia> domkg(1000,50)
0.0027710127400000003

julia> domkg(10000,50)
0.028370805239999988

julia> domkg(100000,50)
0.64326600246
```

sorted adjacency list:
```
julia> domkg(100,50)
0.0013618353199999996

julia> domkg(100,50)
0.0008404460000000002

julia> domkg(100,50)
0.00086414508

julia> domkg(1000,50)
0.007739944119999998

julia> domkg(10000,50)
0.09859604374000001

julia> domkg(100000,50)
1.47696061176
```

**Comment by CarloLucibello** [comment]
well, given all this tests it looks like keeping the adjlist sorted doesn't impact performance too much (this inexplicable to me). So... let's do it

**Comment by sbromberger** [comment]
It appears that for a given average density, the time difference will approach a constant factor as the graph size increases. Does it look hat way to you?

**Comment by CarloLucibello** [comment]
yes, it doesn't seem to have a perceivable scaling with n

**Comment by sbromberger** [comment]
Interesting statistics here: https://github.com/JuliaLang/julia/issues/14112#issuecomment-159727644

**Comment by sbromberger** [comment]
Merged #232 just now.

**Comment by sbromberger** [comment]
We need to now focus on edge iteration. It's very slow.

**Comment by sbromberger** [comment]
Folks, Please take a look at #237 - I would like to merge this by Monday at the latest, assuming no showstoppers. Thanks.

**Comment by sbromberger** [comment]
I'll close this out - we don't have edge indices but I'm still trying to identify a use case for them.
