### ISSUE TITLE
Julia 0.5 roadmap

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#420]
From https://github.com/JuliaLang/METADATA.jl/issues/6155#issuecomment-242997676:

- [x] Tag 0.7.0 from branch `compat-0.5` with a lower bound of Julia `0.5-`
- [x] Keep LG master working on 0.4
- [x] when Julia 0.5 comes out, merge `compat-0.5` (via #428) into master and tag 0.7.1

**Comment by sbromberger** [comment]
I'd like to keep this open until we've tagged a new version.
